### ISSUE TITLE
segmentation model

### ISSUE THREAD

**Issue by tim120526** [Andrew-Qibin/SeeNet#1]
Hi! @Andrew-Qibin , Thanks for sharing your code! I appreciate the Erase method!
 I see you use Deeplab  for segmentation task in paper.  I am a bit confused,  are you use deeplabv2_ASPP to implement  segmentation task based on vgg16 and resnet101 backbone,  i see your paper cite deeplabv2 paper but use Deeplab-LargeFOV. emm.. maybe you use Deeplab-LargeFOV based on vgg16 and use deeplabv2_ASPP based on resnet101? I am confused.
Can u give me some ides? Thank you very much!

**Comment by houqb** [comment]
I just use Deeplab-LargeFOV with ResNet-101. You can also use deeplabv2 with ASPP and let others know what you use. I empirically found Deeplabv2 with ASPP is not that helpful as the version I used.

**Comment by tim120526** [comment]
Get it. Thanks for your advice.

--------------原始邮件--------------
发件人："Qibin (Andrew) Hou "<notifications@github.com>;
发送时间：2018年11月27日(星期二) 晚上9:58
收件人："Andrew-Qibin/SeeNet" <SeeNet@noreply.github.com>;
抄送："tim20120526 "<2111704114@mail2.gdut.edu.cn>;"Author "<author@noreply.github.com>;
主题：Re: [Andrew-Qibin/SeeNet] segmentation model (#1)
-----------------------------------

 
I just use Deeplab-LargeFOV with ResNet-101. You can also use deeplabv2 with ASPP and let others know what you use. I empirically found Deeplabv2 with ASPP is not that helpful as the version I used.
