### ISSUE TITLE
how to generate heatmap

### ISSUE THREAD

**Issue by chaoyan1037** [Andrew-Qibin/SeeNet#2]
Hi Qibin,
Thanks for sharing your code! I have a question about the model. Since your model runs with VOC dataset, which is a multi-label dataset. How do you generate the heatmap? In the original ACoL paper, they can use the last convolutional layer as the heatmap. But in your case, there may by multiple labels. Appreciated for your help!

**Comment by houqb** [comment]
We treat the training process as multiple binary classification problems. So, the BCELoss can be used for each category.

**Comment by chaoyan1037** [comment]
Thanks for the reply! I am sorry that I did not make my question clear. Do you train multiple models and one for each category? Or you just train one model, which conducts multiple binary classifications. 

If it is the second case, there may be multiple activated attention maps. But to erase the intermediate feature maps, you need to generate only one heatmap as shown in your paper. My question is, how do you generate this single heatmap, when you have multiple attention maps. In the reference ACoL paper, since it only has one attention map, so it is easy to use this attention map as the heatmap. 

In your paper, since there may be multiple activated attention maps (one for each positive labels), do you use the average of these multiple attention maps, or use other strategies?

**Comment by houqb** [comment]
We do an element-wise maximum operation among all the attention maps associated with positive labels.
Of course, you can also perform the erasing operation separately.

**Comment by chaoyan1037** [comment]
Got it! Thanks for your reply!
